### ISSUE TITLE
Teleport in the end doesn't work

### ISSUE THREAD

**Issue by Gugi264** [Trainraider/VTeleport#7]
If I teleport to a player who is in the end (regardless if I am in the end or not), I get teleported to the overworld and suffocate somewhere. Didn't test with the nether. Same happens if he tries to teleport when I am in the end.

**Comment by Trainraider** [comment]
I know interdimensional teleportation didn't work in the 1.13, but by the Minecraft 1.15 release, it started working. This was not a bug in the datapack itself.
