### ISSUE TITLE
Datapack doesn't appear to work in 1.15

### ISSUE THREAD

**Issue by shinji257** [Trainraider/VTeleport#8]
I'm trying to use this datapack and I'm running on 1.15.1.  Currently this pack doesn't appear to be working at all.  I can get the book but clicking on an entry just populates the chat with /tell and the player name.  The other person doesn't get any messages on their screen.

**Comment by Trainraider** [comment]
It's tested and working in 1.15.2.

Click the green "[X]" button to the right of the username.
