### ISSUE TITLE
Realm owner unable to tp

### ISSUE THREAD

**Issue by ValaRed** [Trainraider/VTeleport#9]
I just installed this datapack in my realm and my players are able to use the commands, but I cannot.  I can send the request but they do not see it and it just then says "request timed out."

**Comment by Trainraider** [comment]
It works for me as a realm owner. I need more info. Can you outline exactly what you're doing to send a request?

Not sure if this is your issue, but you need to click the green button to the right of the username to send the request. It looks like this: [X]

**Comment by ValaRed** [comment]
It is working today!  I did click the x next to the name and the other players were not seeing anything, but today it’s working great for us all!  Sorry for bothering you!
